<?php
define("YELP_TOKEN","YELP_TOKEN");
define("YELP_SECRET_TOKEN","YELP_SECRET_TOKEN");
define("YELP_CONSUMER_KEY","YELP_CONSUMER_KEY");
define("YELP_CONNSUMER_SECRET","YELP_CONNSUMER_SECRET");
define("FOURSQUARE_CLIENT_ID","FOURSQUARE_CLIENT_ID");
define("FOURSQUARE_SECRET_ID","FOURSQUARE_SECRET_ID");
?>
