<?php
define("YELP_TOKEN","YELP_TOKEN");
define("YELP_SECRET_TOKEN","YELP_SECRET_TOKEN");
define("YELP_CONSUMER_KEY","YELP_CONSUMER_KEY");
define("YELP_CONNSUMER_SECRET","YELP_CONNSUMER_SECRET");
define("FOURSQUARE_CLIENT_ID","FOURSQUARE_CLIENT_ID");
define("FOURSQUARE_SECRET_ID","FOURSQUARE_SECRET_ID");
define('FACEBOOK_APP_ID','YOUR APP ID HERE');
define('FACEBOOK_SECRET','YOUR SECRET HERE');
define('SERVER_LANDING','YOUR SERVER AND PATH HERE');
define('SERVER_REDIRECT','SERVER REDIRECT PAGE TO SHOW THE RESULTS');
define('FACEBOOK_GRAPH_VERSION','YOUR GRAPH VERSION HERE');
?>
